### ISSUE TITLE
Immer 5 Sterne

### ISSUE THREAD

**Issue by mecintosch** [oveleon/contao-recommendation-bundle#1]
Danke für die Erweiterung die ich soeben unter Contao 4.4 getestet habe.

Es werden im Frontend immer 5 Sterne ausgegeben, auch wenn weniger ausgewählt sind. Betrifft beide Frontend Templates.

**Comment by doishub** [comment]
Das haben wir bewusst so implementiert um die Darstellung wie folgt zu gewährleisten:
![image](https://user-images.githubusercontent.com/48379929/60506121-74962c80-9cc5-11e9-890e-ecb805906ba9.png)

Über die CSS-Klasse `active` können die Sterne gestyled oder ausgeblendet werden.

**Comment by eki89** [comment]
Damit man auch ohne CSS Kenntnisse auskommt, könnte die Farbe der Sterne übers Backend einstellbar sein.
Dadurch könnte die Erweiterung on the fly von Anwendern benutzt werden, ohne das Stylesheet anpassen zu müssen.

**Comment by eki89** [comment]
Mit dem neuen Release kann man unter den Einstellungen für Bewertungen eine Standardfarbe für aktive Sterne angeben. Diese werden dann als CSS inline style bei aktiven Punkten ergänzt.

Einzustellen unter Bewertungen -> Einstellungen -> Farbe für aktive Sterne
