### ISSUE TITLE
Feature: schema.org (Rating & AggregateRating)

### ISSUE THREAD

**Issue by Metis77** [oveleon/contao-recommendation-bundle#16]
Is there any way to generate an aggregated ratings view?

**Comment by zoglo** [comment]
@Metis77 
There is no way to generate an aggregated ratings view as of now.
It was requested in this issue: https://github.com/oveleon/contao-google-recommendation-bundle/issues/4.

We did not plan to add one right now, but you are welcome to open a pull request if you would like to add it.

**Comment by Metis77** [comment]
I prepared a template for us, that I could contribute of course.
But as the aggregated items needs to be related to another item (product, organization, ...) I am not sure, if a generic solution is possible.

**Comment by zoglo** [comment]
@Metis77 They could be related to the recommendation archive, couldn't they?

**Comment by Metis77** [comment]
Aggregated ratings need to relate to item (thing) that is being reviewed/rated:
https://schema.org/AggregateRating

Those things can be anything:
[CreativeWork](https://schema.org/CreativeWork)
[Event](https://schema.org/Event)
[Intangible](https://schema.org/Intangible)
[MedicalEntity](https://schema.org/MedicalEntity)
[Organization](https://schema.org/Organization)
[Person](https://schema.org/Person)
[Place](https://schema.org/Place)
[Product](https://schema.org/Product)
...

therefore I dont think a generic solution is possible.

In our specific case I made the rating relate to a product, which could look like this:
```
{
  "@context": "http://schema.org/",
  "@graph": [
    {
      "@type": "Product",
      "name": "Granvogl - Spezialist für bedrucktes Porzellan& Glas",
      "description": "Bearbeitung hochwertiger Produkte aus Porzellan, Glas oder Edelstahl",
      "image": "https://granvogl.com/files/theme/img/PNG/logo_blue.png",
      "sku": "0000",
      "mpn": "0000",
      "brand": {
        "@type": "Brand",
        "name": "Granvogl"
      },
      "offers": {
        "@type": "Offer",
        "availability": "https://schema.org/InStock",
        "price": "10.00",
        "priceCurrency": "EUR",
        "url": "https://granvogl.com/Produkte"
      },
      "review": {
        "@type": "Review",
        "author": {
          "@type": "Person",
          "name": "Anonym"
        }
      },
      "aggregateRating": {
        "@type": "AggregateRating",
        "ratingValue": "5",
        "bestRating": "5",
        "ratingCount": "51"
      }
    }
  ]
}

```

Relating to an event or organization would look totally differen.
So I think there is no generic solution

**Comment by zoglo** [comment]
See: 
- https://github.com/spatie/schema-org/
- https://schema.org/Rating
- https://schema.org/AggregateRating

My approach for ratings would be implementing it via [addSchemaOrg](https://github.com/contao/contao/blob/3b3a551ab2151eb2013916734fae5d828f6011e7/core-bundle/contao/library/Contao/Template.php#L399) and create a new module for aggregated ratings that allows the usage of an archive.
