### ISSUE TITLE
Recommendation wird nicht als Modul angezeigt

### ISSUE THREAD

**Issue by Clyx** [oveleon/contao-recommendation-bundle#2]
Contao-Version: 4.9.13
Theme: ODD-Theme

Installation hat erfolgreich funktioniert und ich kann nun auch die Inhalte der Bewertung pflegen.
Ich kann aber keinen Artikel anlegen mit den Bewertungen. Dies wird vermutlich über Modul -> Bewertungen gemacht, oder?

Eine andere Möglichkeit habe ich auch nicht gefunden

**Comment by eki89** [comment]
Genau, die Bewertungen werden über das Frontend-Modul "Bewertungsliste" ausgegeben. Hier müssen die involvierten Bewertungsarchive ausgewählt werden, da eine Bewertungsliste auch mehrere Archive gleichzeitig ausgeben kann. Also genauso wie bei News und Events.
Für umfangreicheren Bewertungen kann man zusätzlich einen Bewertungsleser einbinden, welcher eine Bewertung ebenfalls wie bei News auf einer Detailseite ausgibt.

**Comment by Clyx** [comment]
Hat funktioniert, vielen Dank
