### ISSUE TITLE
Improve field definition for form (order and mandatory)

### ISSUE THREAD

**Issue by cliffparnitzky** [oveleon/contao-recommendation-bundle#22]
### Prerequisites

- [X] I [checked](https://github.com/oveleon/contao-recommendation-bundle/issues?q=is%3Aissue) for duplicate feature requests (open and closed)
- [X] I have read the [contributing guidelines](https://github.com/oveleon/contao-recommendation-bundle#bugs-and-feature-requests)

### Proposal

A configuration possibility for the order and mandatory definition of the form fields would be nice.

### Context

There may be different feelings, which order the fields of the form should have and which field has to be filled (mandatory) or not.

**Comment by cliffparnitzky** [comment]
Just to mention: a current workaround may be to define a order for the optional fields in the backend module, which results in the frontend. Not that fancy, how it could be.

**Comment by zoglo** [comment]
**Closed as stale - [Request features](https://www.oveleon.de/contao-entwicklung.html#angebot-anfordern) if needed**
