### ISSUE TITLE
Bildgrößen werden ignoriert

### ISSUE THREAD

**Issue by sebssch** [oveleon/contao-recommendation-bundle#3]
Folgende Zeile verhindert, dass Bildgrößen welche über eine .yml Datei konfiguriert wurden nicht funktionieren. 
Bildgrößen über das Backend werden mit einer ID aufgerufen. Bildgrößen in der .yml Datei über den Namen mit einem vorangestellten "_". 

<img width="527" alt="Modu… 2021-07-20 14-21-42" src="https://user-images.githubusercontent.com/18069290/126794098-428a516b-854a-40ce-b89f-1a6c8325a326.png">

**Comment by zoglo** [comment]
Hi @sebssch ,

vielen Dank für dein Issue. Das Problem wird mit dem nächsten Release behoben.
Wir haben noch andere Features für das Bundle geplant, welche wir noch integrieren wollen.

Vorerst könntest du die dev-master installieren. Mit der Fehlerbehebung endet auch der Support für Contao 4.4 / PHP 5.6.

**Comment by zoglo** [comment]
Hi @sebssch 

vor einigen Minuten haben wir eine neue Version des Contao Recommendation Bundle released. Könntest du deinen Fehler nochmal testen?

https://github.com/oveleon/contao-recommendation-bundle/releases/tag/1.1.0

**Comment by sebssch** [comment]
Funktioniert! Prima!
