### ISSUE TITLE
Bundle doesn't work with Contao 4.13

### ISSUE THREAD

**Issue by Matheoz-sys** [oveleon/contao-recommendation-bundle#8]
It seems "patchwork/utf8" doesn't exist in the newest contao version, but it's used in ModuleRecommendationList.php line=52.

**Comment by Matheoz-sys** [comment]
I've been using it as dependency from "contao-google-recommendation-bundle", where still was version ^1.1. After installation contao-recommendation-bundle it works again.

**Comment by zoglo** [comment]
Hey @Matheoz-sys ,
I've updated the composer.json for the google-recommendation-bundle and released it as Version 1.2.1
https://github.com/oveleon/contao-google-recommendation-bundle/releases/tag/1.2.1
