### ISSUE TITLE
Bewertung als Inhaltselement

### ISSUE THREAD

**Issue by sebssch** [oveleon/contao-recommendation-bundle#9]
Vorschläge, das Bundle zu erweitern:

### Einzelne Bewertung auswählen
Ein Inhaltselement, welches die Option bietet eine einzelne Bewertung aus einem Archiv zu selektieren, um dieses in einer Nachricht oder einem Artikel ausgeben zu können. 

### Inhaltselement 
Eigenes Inhaltselement mit den Feldern einer Bewertung nur eben ohne Referenzierung zu einem Archiv.

**Comment by zoglo** [comment]
Stale - Able to [request features](https://www.oveleon.de/contao-entwicklung.html#angebot-anfordern) if needed
